### ISSUE TITLE
Implementation with bolt

### ISSUE THREAD

**Issue by brunowego** [griffinsockwell/react-firebase-crud#1]
Nice code here @griffinsockwell, congrats!

I think the code below is the same of your json security but with bolt:

``` bolt
path / {
  read() { false }
  write() { false }
}

path /tasks {
  read() { true }
  write() { true }
}

path /tasks/{task} is Task;

type Task {
  text: String,
  checked: Boolean,
  starred: Boolean,
  timestamp: Number
}
```

You have tried before with bolt?

**Comment by griffinsockwell** [comment]
I have not tried bolt yet, but I should. At some point when I update this sample app I will make sure to try bolt.

**Comment by griffinsockwell** [comment]
I updated the app and I changed the security rules over to bolt with the code you wrote. You can find it [here](https://github.com/griffinsockwell/react-firebase-crud/blob/master/TaskAppWeb/rules.bolt). Thanks for your help @brunowego!
